// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.

package org.springsource.roo.extrack.client.managed.activity;

import com.google.gwt.activity.shared.Activity;
import com.google.gwt.activity.shared.ActivityMapper;
import com.google.gwt.place.shared.Place;
import com.google.gwt.place.shared.PlaceController;
import com.google.inject.Inject;
import org.springsource.roo.extrack.client.managed.request.ApplicationEntityTypesProcessor;
import org.springsource.roo.extrack.client.managed.request.ApplicationRequestFactory;
import org.springsource.roo.extrack.client.managed.ui.EmployeeListView;
import org.springsource.roo.extrack.client.managed.ui.EmployeeMobileListView;
import org.springsource.roo.extrack.client.managed.ui.ExpenseListView;
import org.springsource.roo.extrack.client.managed.ui.ExpenseMobileListView;
import org.springsource.roo.extrack.client.managed.ui.ReportListView;
import org.springsource.roo.extrack.client.managed.ui.ReportMobileListView;
import org.springsource.roo.extrack.client.proxy.EmployeeProxy;
import org.springsource.roo.extrack.client.proxy.ExpenseProxy;
import org.springsource.roo.extrack.client.proxy.ReportProxy;
import org.springsource.roo.extrack.client.scaffold.ScaffoldApp;
import org.springsource.roo.extrack.client.scaffold.place.ProxyListPlace;

public abstract class ApplicationMasterActivities_Roo_Gwt implements ActivityMapper {

    protected ApplicationRequestFactory requests;

    protected PlaceController placeController;

    public Activity getActivity(Place place) {
        if (!(place instanceof ProxyListPlace)) {
            return null;
        }
        ProxyListPlace listPlace = (ProxyListPlace) place;
        return new ApplicationEntityTypesProcessor<Activity>() {

            @Override
            public void handleEmployee(EmployeeProxy isNull) {
                setResult(new EmployeeListActivity(requests, ScaffoldApp.isMobile() ? EmployeeMobileListView.instance() : EmployeeListView.instance(), placeController));
            }

            @Override
            public void handleExpense(ExpenseProxy isNull) {
                setResult(new ExpenseListActivity(requests, ScaffoldApp.isMobile() ? ExpenseMobileListView.instance() : ExpenseListView.instance(), placeController));
            }

            @Override
            public void handleReport(ReportProxy isNull) {
                setResult(new ReportListActivity(requests, ScaffoldApp.isMobile() ? ReportMobileListView.instance() : ReportListView.instance(), placeController));
            }
        }.process(listPlace.getProxyClass());
    }
}
