// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.

package org.springsource.roo.extrack.client.managed.activity;

import com.google.gwt.activity.shared.Activity;
import com.google.gwt.place.shared.PlaceController;
import com.google.web.bindery.requestfactory.shared.EntityProxyId;
import com.google.web.bindery.requestfactory.shared.RequestContext;
import org.springsource.roo.extrack.client.managed.request.ApplicationRequestFactory;
import org.springsource.roo.extrack.client.managed.ui.EmployeeDetailsView;
import org.springsource.roo.extrack.client.managed.ui.EmployeeEditView;
import org.springsource.roo.extrack.client.managed.ui.EmployeeListView;
import org.springsource.roo.extrack.client.managed.ui.EmployeeMobileDetailsView;
import org.springsource.roo.extrack.client.managed.ui.EmployeeMobileEditView;
import org.springsource.roo.extrack.client.proxy.EmployeeProxy;
import org.springsource.roo.extrack.client.request.EmployeeRequest;
import org.springsource.roo.extrack.client.scaffold.ScaffoldApp;
import org.springsource.roo.extrack.client.scaffold.place.CreateAndEditProxy;
import org.springsource.roo.extrack.client.scaffold.place.FindAndEditProxy;
import org.springsource.roo.extrack.client.scaffold.place.ProxyPlace;
import org.springsource.roo.extrack.shared.domain.Gender;

public abstract class EmployeeActivitiesMapper_Roo_Gwt {

    protected ApplicationRequestFactory requests;

    protected PlaceController placeController;

    protected Activity makeCreateActivity() {
        EmployeeEditView.instance().setCreating(true);
        final EmployeeRequest request = requests.employeeRequest();
        Activity activity = new CreateAndEditProxy<EmployeeProxy>(EmployeeProxy.class, request, ScaffoldApp.isMobile() ? EmployeeMobileEditView.instance() : EmployeeEditView.instance(), placeController) {

            @Override
            protected RequestContext createSaveRequest(EmployeeProxy proxy) {
                request.persist().using(proxy);
                return request;
            }
        };
        return new EmployeeEditActivityWrapper(requests, ScaffoldApp.isMobile() ? EmployeeMobileEditView.instance() : EmployeeEditView.instance(), activity, null);
    }

    @SuppressWarnings("unchecked")
    protected EntityProxyId<org.springsource.roo.extrack.client.proxy.EmployeeProxy> coerceId(ProxyPlace place) {
        return (EntityProxyId<EmployeeProxy>) place.getProxyId();
    }

    protected Activity makeEditActivity(ProxyPlace place) {
        EmployeeEditView.instance().setCreating(false);
        EntityProxyId<EmployeeProxy> proxyId = coerceId(place);
        Activity activity = new FindAndEditProxy<EmployeeProxy>(proxyId, requests, ScaffoldApp.isMobile() ? EmployeeMobileEditView.instance() : EmployeeEditView.instance(), placeController) {

            @Override
            protected RequestContext createSaveRequest(EmployeeProxy proxy) {
                EmployeeRequest request = requests.employeeRequest();
                request.persist().using(proxy);
                return request;
            }
        };
        return new EmployeeEditActivityWrapper(requests, ScaffoldApp.isMobile() ? EmployeeMobileEditView.instance() : EmployeeEditView.instance(), activity, proxyId);
    }
}
