// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.

package org.springsource.roo.extrack.client.managed.activity;

import com.google.gwt.place.shared.Place;
import com.google.gwt.place.shared.PlaceController;
import com.google.gwt.view.client.Range;
import com.google.web.bindery.requestfactory.shared.Receiver;
import com.google.web.bindery.requestfactory.shared.Request;
import java.util.List;
import org.springsource.roo.extrack.client.managed.request.ApplicationRequestFactory;
import org.springsource.roo.extrack.client.proxy.EmployeeProxy;
import org.springsource.roo.extrack.client.scaffold.ScaffoldMobileApp;
import org.springsource.roo.extrack.client.scaffold.activity.IsScaffoldMobileActivity;
import org.springsource.roo.extrack.client.scaffold.place.AbstractProxyListActivity;
import org.springsource.roo.extrack.client.scaffold.place.ProxyListView;
import org.springsource.roo.extrack.shared.domain.Gender;

public abstract class EmployeeListActivity_Roo_Gwt extends AbstractProxyListActivity<EmployeeProxy> implements IsScaffoldMobileActivity {

    protected ApplicationRequestFactory requests;

    public EmployeeListActivity_Roo_Gwt(PlaceController placeController, ProxyListView<org.springsource.roo.extrack.client.proxy.EmployeeProxy> view, Class<org.springsource.roo.extrack.client.proxy.EmployeeProxy> proxyType) {
        super(placeController, view, proxyType);
    }

    protected void fireCountRequest(Receiver<java.lang.Long> callback) {
        requests.employeeRequest().countEmployees().fire(callback);
    }
}
