// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.

package org.springsource.roo.extrack.client.managed.activity;

import com.google.gwt.activity.shared.Activity;
import com.google.gwt.place.shared.PlaceController;
import com.google.web.bindery.requestfactory.shared.EntityProxyId;
import com.google.web.bindery.requestfactory.shared.RequestContext;
import org.springsource.roo.extrack.client.managed.request.ApplicationRequestFactory;
import org.springsource.roo.extrack.client.managed.ui.ExpenseDetailsView;
import org.springsource.roo.extrack.client.managed.ui.ExpenseEditView;
import org.springsource.roo.extrack.client.managed.ui.ExpenseListView;
import org.springsource.roo.extrack.client.managed.ui.ExpenseMobileDetailsView;
import org.springsource.roo.extrack.client.managed.ui.ExpenseMobileEditView;
import org.springsource.roo.extrack.client.proxy.ExpenseProxy;
import org.springsource.roo.extrack.client.proxy.ReportProxy;
import org.springsource.roo.extrack.client.request.ExpenseRequest;
import org.springsource.roo.extrack.client.scaffold.ScaffoldApp;
import org.springsource.roo.extrack.client.scaffold.place.CreateAndEditProxy;
import org.springsource.roo.extrack.client.scaffold.place.FindAndEditProxy;
import org.springsource.roo.extrack.client.scaffold.place.ProxyPlace;

public abstract class ExpenseActivitiesMapper_Roo_Gwt {

    protected ApplicationRequestFactory requests;

    protected PlaceController placeController;

    protected Activity makeCreateActivity() {
        ExpenseEditView.instance().setCreating(true);
        final ExpenseRequest request = requests.expenseRequest();
        Activity activity = new CreateAndEditProxy<ExpenseProxy>(ExpenseProxy.class, request, ScaffoldApp.isMobile() ? ExpenseMobileEditView.instance() : ExpenseEditView.instance(), placeController) {

            @Override
            protected RequestContext createSaveRequest(ExpenseProxy proxy) {
                request.persist().using(proxy);
                return request;
            }
        };
        return new ExpenseEditActivityWrapper(requests, ScaffoldApp.isMobile() ? ExpenseMobileEditView.instance() : ExpenseEditView.instance(), activity, null);
    }

    @SuppressWarnings("unchecked")
    protected EntityProxyId<org.springsource.roo.extrack.client.proxy.ExpenseProxy> coerceId(ProxyPlace place) {
        return (EntityProxyId<ExpenseProxy>) place.getProxyId();
    }

    protected Activity makeEditActivity(ProxyPlace place) {
        ExpenseEditView.instance().setCreating(false);
        EntityProxyId<ExpenseProxy> proxyId = coerceId(place);
        Activity activity = new FindAndEditProxy<ExpenseProxy>(proxyId, requests, ScaffoldApp.isMobile() ? ExpenseMobileEditView.instance() : ExpenseEditView.instance(), placeController) {

            @Override
            protected RequestContext createSaveRequest(ExpenseProxy proxy) {
                ExpenseRequest request = requests.expenseRequest();
                request.persist().using(proxy);
                return request;
            }
        };
        return new ExpenseEditActivityWrapper(requests, ScaffoldApp.isMobile() ? ExpenseMobileEditView.instance() : ExpenseEditView.instance(), activity, proxyId);
    }
}
