// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.

package org.springsource.roo.extrack.client.managed.activity;

import com.google.gwt.activity.shared.Activity;
import com.google.gwt.event.shared.EventBus;
import com.google.gwt.place.shared.Place;
import com.google.gwt.user.client.ui.AcceptsOneWidget;
import com.google.web.bindery.requestfactory.shared.EntityProxyId;
import com.google.web.bindery.requestfactory.shared.Receiver;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Collection;
import java.util.Collections;
import java.util.List;
import org.springsource.roo.extrack.client.managed.activity.ExpenseEditActivityWrapper.View;
import org.springsource.roo.extrack.client.managed.request.ApplicationRequestFactory;
import org.springsource.roo.extrack.client.proxy.ExpenseProxy;
import org.springsource.roo.extrack.client.proxy.ReportProxy;
import org.springsource.roo.extrack.client.scaffold.activity.IsScaffoldMobileActivity;
import org.springsource.roo.extrack.client.scaffold.place.ProxyEditView;
import org.springsource.roo.extrack.client.scaffold.place.ProxyListPlace;
import org.springsource.roo.extrack.client.scaffold.place.ProxyPlace;

public abstract class ExpenseEditActivityWrapper_Roo_Gwt implements Activity, IsScaffoldMobileActivity {

    protected Activity wrapped;

    protected View<?> view;

    protected ApplicationRequestFactory requests;

    @Override
    public void start(AcceptsOneWidget display, EventBus eventBus) {
        view.setReportPickerValues(Collections.<ReportProxy>emptyList());
        requests.reportRequest().findReportEntries(0, 50).with(org.springsource.roo.extrack.client.managed.ui.ReportProxyRenderer.instance().getPaths()).fire(new Receiver<List<ReportProxy>>() {

            public void onSuccess(List<ReportProxy> response) {
                List<ReportProxy> values = new ArrayList<ReportProxy>();
                values.add(null);
                values.addAll(response);
                view.setReportPickerValues(values);
            }
        });
        wrapped.start(display, eventBus);
    }
}
