// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.

package org.springsource.roo.extrack.client.managed.activity;

import com.google.gwt.activity.shared.Activity;
import com.google.gwt.event.shared.EventBus;
import com.google.gwt.place.shared.Place;
import com.google.gwt.user.client.ui.AcceptsOneWidget;
import com.google.web.bindery.requestfactory.shared.EntityProxyId;
import com.google.web.bindery.requestfactory.shared.Receiver;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Collection;
import java.util.Collections;
import java.util.List;
import org.springsource.roo.extrack.client.managed.activity.ReportEditActivityWrapper.View;
import org.springsource.roo.extrack.client.managed.request.ApplicationRequestFactory;
import org.springsource.roo.extrack.client.proxy.EmployeeProxy;
import org.springsource.roo.extrack.client.proxy.ReportProxy;
import org.springsource.roo.extrack.client.scaffold.activity.IsScaffoldMobileActivity;
import org.springsource.roo.extrack.client.scaffold.place.ProxyEditView;
import org.springsource.roo.extrack.client.scaffold.place.ProxyListPlace;
import org.springsource.roo.extrack.client.scaffold.place.ProxyPlace;

public abstract class ReportEditActivityWrapper_Roo_Gwt implements Activity, IsScaffoldMobileActivity {

    protected Activity wrapped;

    protected View<?> view;

    protected ApplicationRequestFactory requests;

    @Override
    public void start(AcceptsOneWidget display, EventBus eventBus) {
        view.setReporterPickerValues(Collections.<EmployeeProxy>emptyList());
        requests.employeeRequest().findEmployeeEntries(0, 50).with(org.springsource.roo.extrack.client.managed.ui.EmployeeProxyRenderer.instance().getPaths()).fire(new Receiver<List<EmployeeProxy>>() {

            public void onSuccess(List<EmployeeProxy> response) {
                List<EmployeeProxy> values = new ArrayList<EmployeeProxy>();
                values.add(null);
                values.addAll(response);
                view.setReporterPickerValues(values);
            }
        });
        view.setApprovedSupervisorPickerValues(Collections.<EmployeeProxy>emptyList());
        requests.employeeRequest().findEmployeeEntries(0, 50).with(org.springsource.roo.extrack.client.managed.ui.EmployeeProxyRenderer.instance().getPaths()).fire(new Receiver<List<EmployeeProxy>>() {

            public void onSuccess(List<EmployeeProxy> response) {
                List<EmployeeProxy> values = new ArrayList<EmployeeProxy>();
                values.add(null);
                values.addAll(response);
                view.setApprovedSupervisorPickerValues(values);
            }
        });
        wrapped.start(display, eventBus);
    }
}
