// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.

package org.springsource.roo.extrack.client.managed.ui;

import com.google.gwt.text.shared.AbstractRenderer;
import org.springsource.roo.extrack.client.managed.request.ApplicationEntityTypesProcessor;
import org.springsource.roo.extrack.client.proxy.EmployeeProxy;
import org.springsource.roo.extrack.client.proxy.ExpenseProxy;
import org.springsource.roo.extrack.client.proxy.ReportProxy;
import org.springsource.roo.extrack.client.scaffold.place.ProxyListPlace;

public abstract class ApplicationListPlaceRenderer_Roo_Gwt extends AbstractRenderer<ProxyListPlace> {

    public String render(ProxyListPlace object) {
        return new ApplicationEntityTypesProcessor<String>() {

            @Override
            public void handleEmployee(EmployeeProxy isNull) {
                setResult("Employees");
            }

            @Override
            public void handleExpense(ExpenseProxy isNull) {
                setResult("Expenses");
            }

            @Override
            public void handleReport(ReportProxy isNull) {
                setResult("Reports");
            }
        }.process(object.getProxyClass());
    }
}
