// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.

package org.springsource.roo.extrack.client.managed.ui;

import com.google.gwt.core.client.GWT;
import com.google.gwt.dom.client.SpanElement;
import com.google.gwt.event.dom.client.ClickEvent;
import com.google.gwt.event.dom.client.HasClickHandlers;
import com.google.gwt.i18n.client.DateTimeFormat;
import com.google.gwt.i18n.client.NumberFormat;
import com.google.gwt.uibinder.client.UiBinder;
import com.google.gwt.uibinder.client.UiField;
import com.google.gwt.uibinder.client.UiHandler;
import com.google.gwt.user.client.Window;
import com.google.gwt.user.client.ui.Composite;
import com.google.gwt.user.client.ui.HTMLPanel;
import com.google.gwt.user.client.ui.Widget;
import org.springsource.roo.extrack.client.proxy.ExpenseProxy;
import org.springsource.roo.extrack.client.proxy.ReportProxy;
import org.springsource.roo.extrack.client.scaffold.place.ProxyDetailsView;
import org.springsource.roo.extrack.client.scaffold.place.ProxyListView;

public abstract class ExpenseDetailsView_Roo_Gwt extends Composite implements ProxyDetailsView<ExpenseProxy> {

    @UiField
    SpanElement id;

    @UiField
    SpanElement amount;

    @UiField
    SpanElement description;

    @UiField
    SpanElement report;

    @UiField
    SpanElement approval;

    @UiField
    SpanElement category;

    @UiField
    SpanElement created;

    @UiField
    SpanElement reasonDenied;

    @UiField
    SpanElement version;

    ExpenseProxy proxy;

    @UiField
    SpanElement displayRenderer;

    public void setValue(ExpenseProxy proxy) {
        this.proxy = proxy;
        id.setInnerText(proxy.getId() == null ? "" : String.valueOf(proxy.getId()));
        amount.setInnerText(proxy.getAmount() == null ? "" : String.valueOf(proxy.getAmount()));
        description.setInnerText(proxy.getDescription() == null ? "" : String.valueOf(proxy.getDescription()));
        report.setInnerText(proxy.getReport() == null ? "" : org.springsource.roo.extrack.client.managed.ui.ReportProxyRenderer.instance().render(proxy.getReport()));
        approval.setInnerText(proxy.getApproval() == null ? "" : String.valueOf(proxy.getApproval()));
        category.setInnerText(proxy.getCategory() == null ? "" : String.valueOf(proxy.getCategory()));
        created.setInnerText(proxy.getCreated() == null ? "" : DateTimeFormat.getFormat(DateTimeFormat.PredefinedFormat.DATE_SHORT).format(proxy.getCreated()));
        reasonDenied.setInnerText(proxy.getReasonDenied() == null ? "" : String.valueOf(proxy.getReasonDenied()));
        version.setInnerText(proxy.getVersion() == null ? "" : String.valueOf(proxy.getVersion()));
        displayRenderer.setInnerText(ExpenseProxyRenderer.instance().render(proxy));
    }
}
