// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.

package org.springsource.roo.extrack.client.managed.ui;

import com.google.gwt.core.client.GWT;
import com.google.gwt.dom.client.SpanElement;
import com.google.gwt.event.dom.client.ClickEvent;
import com.google.gwt.event.dom.client.HasClickHandlers;
import com.google.gwt.i18n.client.DateTimeFormat;
import com.google.gwt.i18n.client.NumberFormat;
import com.google.gwt.uibinder.client.UiBinder;
import com.google.gwt.uibinder.client.UiField;
import com.google.gwt.uibinder.client.UiHandler;
import com.google.gwt.user.client.Window;
import com.google.gwt.user.client.ui.Composite;
import com.google.gwt.user.client.ui.HTMLPanel;
import com.google.gwt.user.client.ui.Widget;
import org.springsource.roo.extrack.client.proxy.EmployeeProxy;
import org.springsource.roo.extrack.client.proxy.ReportProxy;
import org.springsource.roo.extrack.client.scaffold.place.ProxyDetailsView;
import org.springsource.roo.extrack.client.scaffold.place.ProxyListView;

public abstract class ReportDetailsView_Roo_Gwt extends Composite implements ProxyDetailsView<ReportProxy> {

    @UiField
    SpanElement id;

    @UiField
    SpanElement purpose;

    @UiField
    SpanElement notes;

    @UiField
    SpanElement created;

    @UiField
    SpanElement department;

    @UiField
    SpanElement reporter;

    @UiField
    SpanElement approvedSupervisor;

    @UiField
    SpanElement version;

    ReportProxy proxy;

    @UiField
    SpanElement displayRenderer;

    public void setValue(ReportProxy proxy) {
        this.proxy = proxy;
        id.setInnerText(proxy.getId() == null ? "" : String.valueOf(proxy.getId()));
        purpose.setInnerText(proxy.getPurpose() == null ? "" : String.valueOf(proxy.getPurpose()));
        notes.setInnerText(proxy.getNotes() == null ? "" : String.valueOf(proxy.getNotes()));
        created.setInnerText(proxy.getCreated() == null ? "" : DateTimeFormat.getFormat(DateTimeFormat.PredefinedFormat.DATE_SHORT).format(proxy.getCreated()));
        department.setInnerText(proxy.getDepartment() == null ? "" : String.valueOf(proxy.getDepartment()));
        reporter.setInnerText(proxy.getReporter() == null ? "" : org.springsource.roo.extrack.client.managed.ui.EmployeeProxyRenderer.instance().render(proxy.getReporter()));
        approvedSupervisor.setInnerText(proxy.getApprovedSupervisor() == null ? "" : org.springsource.roo.extrack.client.managed.ui.EmployeeProxyRenderer.instance().render(proxy.getApprovedSupervisor()));
        version.setInnerText(proxy.getVersion() == null ? "" : String.valueOf(proxy.getVersion()));
        displayRenderer.setInnerText(ReportProxyRenderer.instance().render(proxy));
    }
}
