// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.

package org.springsource.roo.extrack.client.managed.ui;

import com.google.gwt.i18n.client.DateTimeFormat;
import com.google.gwt.i18n.client.NumberFormat;
import com.google.gwt.safehtml.shared.SafeHtml;
import com.google.gwt.safehtml.shared.SafeHtmlBuilder;
import com.google.gwt.safehtml.shared.SafeHtmlUtils;
import com.google.gwt.text.client.DateTimeFormatRenderer;
import com.google.gwt.text.shared.AbstractRenderer;
import com.google.gwt.text.shared.AbstractSafeHtmlRenderer;
import com.google.gwt.text.shared.Renderer;
import com.google.gwt.text.shared.SafeHtmlRenderer;
import java.util.HashSet;
import java.util.Set;
import org.springsource.roo.extrack.client.proxy.EmployeeProxy;
import org.springsource.roo.extrack.client.proxy.ReportProxy;
import org.springsource.roo.extrack.client.scaffold.ScaffoldMobileApp;
import org.springsource.roo.extrack.client.scaffold.ui.MobileProxyListView;

public abstract class ReportMobileListView_Roo_Gwt extends MobileProxyListView<ReportProxy> {

    protected Set<String> paths = new HashSet<String>();

    public ReportMobileListView_Roo_Gwt(String buttonText, SafeHtmlRenderer<org.springsource.roo.extrack.client.proxy.ReportProxy> renderer) {
        super(buttonText, renderer);
    }

    public void init() {
        paths.add("purpose");
        paths.add("notes");
        paths.add("created");
    }
}
