// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.

package org.springsource.roo.extrack.client.managed.request;

import org.springsource.roo.extrack.client.request.EmployeeRequest;
import org.springsource.roo.extrack.client.request.ExpenseRequest;
import org.springsource.roo.extrack.client.request.ReportRequest;
import org.springsource.roo.extrack.shared.scaffold.ScaffoldRequestFactory;

public interface ApplicationRequestFactory extends ScaffoldRequestFactory {

    EmployeeRequest employeeRequest();

    ExpenseRequest expenseRequest();

    ReportRequest reportRequest();
}
