// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.

package org.springsource.roo.extrack.client.managed.request;

import com.google.web.bindery.requestfactory.shared.EntityProxy;
import java.util.Collections;
import java.util.HashSet;
import java.util.Set;
import org.springsource.roo.extrack.client.proxy.EmployeeProxy;
import org.springsource.roo.extrack.client.proxy.ExpenseProxy;
import org.springsource.roo.extrack.client.proxy.ReportProxy;

public abstract class ApplicationEntityTypesProcessor<T> {

    private final T defaultValue;

    private T result;

    public ApplicationEntityTypesProcessor() {
        defaultValue = null;
    }

    public ApplicationEntityTypesProcessor(T defaultValue) {
        this.defaultValue = defaultValue;
    }

    public static Set<java.lang.Class<? extends com.google.web.bindery.requestfactory.shared.EntityProxy>> getAll() {
        Set<Class<? extends EntityProxy>> rtn = new HashSet<Class<? extends EntityProxy>>();
        rtn.add(EmployeeProxy.class);
        rtn.add(ExpenseProxy.class);
        rtn.add(ReportProxy.class);
        return Collections.unmodifiableSet(rtn);
    }

    private static void process(org.springsource.roo.extrack.client.managed.request.ApplicationEntityTypesProcessor<?> processor, Class<?> clazz) {
        if (EmployeeProxy.class.equals(clazz)) {
            processor.handleEmployee((EmployeeProxy) null);
            return;
        }
        if (ExpenseProxy.class.equals(clazz)) {
            processor.handleExpense((ExpenseProxy) null);
            return;
        }
        if (ReportProxy.class.equals(clazz)) {
            processor.handleReport((ReportProxy) null);
            return;
        }
        processor.handleNonProxy(null);
    }

    private static void process(org.springsource.roo.extrack.client.managed.request.ApplicationEntityTypesProcessor<?> processor, Object proxy) {
        if (proxy instanceof EmployeeProxy) {
            processor.handleEmployee((EmployeeProxy) proxy);
            return;
        }
        if (proxy instanceof ExpenseProxy) {
            processor.handleExpense((ExpenseProxy) proxy);
            return;
        }
        if (proxy instanceof ReportProxy) {
            processor.handleReport((ReportProxy) proxy);
            return;
        }
        processor.handleNonProxy(proxy);
    }

    public void handleNonProxy(Object object) {
    }

    public abstract void handleEmployee(EmployeeProxy proxy);

    public abstract void handleExpense(ExpenseProxy proxy);

    public abstract void handleReport(ReportProxy proxy);

    public T process(Class<?> clazz) {
        setResult(defaultValue);
        ApplicationEntityTypesProcessor.process(this, clazz);
        return result;
    }

    public T process(Object proxy) {
        setResult(defaultValue);
        ApplicationEntityTypesProcessor.process(this, proxy);
        return result;
    }

    protected void setResult(T result) {
        this.result = result;
    }
}
