// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.springsource.roo.extrack.server.domain;

import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.stereotype.Component;
import org.springsource.roo.extrack.server.domain.Employee;
import org.springsource.roo.extrack.server.domain.EmployeeDataOnDemand;
import org.springsource.roo.extrack.shared.domain.Gender;

privileged aspect EmployeeDataOnDemand_Roo_DataOnDemand {
    
    declare @type: EmployeeDataOnDemand: @Component;
    
    private Random EmployeeDataOnDemand.rnd = new SecureRandom();
    
    private List<Employee> EmployeeDataOnDemand.data;
    
    public Employee EmployeeDataOnDemand.getNewTransientEmployee(int index) {
        Employee obj = new Employee();
        setAdmin(obj, index);
        setDepartment(obj, index);
        setDisplayName(obj, index);
        setGender(obj, index);
        setSupervisor(obj, index);
        setUserName(obj, index);
        return obj;
    }
    
    public void EmployeeDataOnDemand.setAdmin(Employee obj, int index) {
        Boolean admin = Boolean.TRUE;
        obj.setAdmin(admin);
    }
    
    public void EmployeeDataOnDemand.setDepartment(Employee obj, int index) {
        String department = "department_" + index;
        obj.setDepartment(department);
    }
    
    public void EmployeeDataOnDemand.setDisplayName(Employee obj, int index) {
        String displayName = "displayName_" + index;
        obj.setDisplayName(displayName);
    }
    
    public void EmployeeDataOnDemand.setGender(Employee obj, int index) {
        Gender gender = Gender.class.getEnumConstants()[0];
        obj.setGender(gender);
    }
    
    public void EmployeeDataOnDemand.setSupervisor(Employee obj, int index) {
        Employee supervisor = obj;
        obj.setSupervisor(supervisor);
    }
    
    public void EmployeeDataOnDemand.setUserName(Employee obj, int index) {
        String userName = "userName_" + index;
        if (userName.length() > 30) {
            userName = userName.substring(0, 30);
        }
        obj.setUserName(userName);
    }
    
    public Employee EmployeeDataOnDemand.getSpecificEmployee(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        Employee obj = data.get(index);
        Long id = obj.getId();
        return Employee.findEmployee(id);
    }
    
    public Employee EmployeeDataOnDemand.getRandomEmployee() {
        init();
        Employee obj = data.get(rnd.nextInt(data.size()));
        Long id = obj.getId();
        return Employee.findEmployee(id);
    }
    
    public boolean EmployeeDataOnDemand.modifyEmployee(Employee obj) {
        return false;
    }
    
    public void EmployeeDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = Employee.findEmployeeEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'Employee' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<Employee>();
        for (int i = 0; i < 10; i++) {
            Employee obj = getNewTransientEmployee(i);
            try {
                obj.persist();
            } catch (ConstraintViolationException e) {
                StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getConstraintDescriptor()).append(":").append(cv.getMessage()).append("=").append(cv.getInvalidValue()).append("]");
                }
                throw new RuntimeException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
