// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.springsource.roo.extrack.server.domain;

import org.springframework.beans.factory.annotation.Configurable;
import org.springsource.roo.extrack.server.domain.EmployeeDataOnDemand;

privileged aspect EmployeeDataOnDemand_Roo_Configurable {
    
    declare @type: EmployeeDataOnDemand: @Configurable;
    
}
