// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.springsource.roo.extrack.server.domain;

import java.util.List;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;
import org.springsource.roo.extrack.server.domain.Report;
import org.springsource.roo.extrack.server.domain.ReportDataOnDemand;
import org.springsource.roo.extrack.server.domain.ReportIntegrationTest;

privileged aspect ReportIntegrationTest_Roo_IntegrationTest {
    
    declare @type: ReportIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: ReportIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext*.xml");
    
    declare @type: ReportIntegrationTest: @Transactional;
    
    @Autowired
    private ReportDataOnDemand ReportIntegrationTest.dod;
    
    @Test
    public void ReportIntegrationTest.testCountReports() {
        Assert.assertNotNull("Data on demand for 'Report' failed to initialize correctly", dod.getRandomReport());
        long count = Report.countReports();
        Assert.assertTrue("Counter for 'Report' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void ReportIntegrationTest.testFindReport() {
        Report obj = dod.getRandomReport();
        Assert.assertNotNull("Data on demand for 'Report' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Report' failed to provide an identifier", id);
        obj = Report.findReport(id);
        Assert.assertNotNull("Find method for 'Report' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'Report' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void ReportIntegrationTest.testFindAllReports() {
        Assert.assertNotNull("Data on demand for 'Report' failed to initialize correctly", dod.getRandomReport());
        long count = Report.countReports();
        Assert.assertTrue("Too expensive to perform a find all test for 'Report', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<Report> result = Report.findAllReports();
        Assert.assertNotNull("Find all method for 'Report' illegally returned null", result);
        Assert.assertTrue("Find all method for 'Report' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void ReportIntegrationTest.testFindReportEntries() {
        Assert.assertNotNull("Data on demand for 'Report' failed to initialize correctly", dod.getRandomReport());
        long count = Report.countReports();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<Report> result = Report.findReportEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'Report' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'Report' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void ReportIntegrationTest.testFlush() {
        Report obj = dod.getRandomReport();
        Assert.assertNotNull("Data on demand for 'Report' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Report' failed to provide an identifier", id);
        obj = Report.findReport(id);
        Assert.assertNotNull("Find method for 'Report' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyReport(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'Report' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void ReportIntegrationTest.testMergeUpdate() {
        Report obj = dod.getRandomReport();
        Assert.assertNotNull("Data on demand for 'Report' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Report' failed to provide an identifier", id);
        obj = Report.findReport(id);
        boolean modified =  dod.modifyReport(obj);
        Integer currentVersion = obj.getVersion();
        Report merged = obj.merge();
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'Report' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void ReportIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'Report' failed to initialize correctly", dod.getRandomReport());
        Report obj = dod.getNewTransientReport(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'Report' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'Report' identifier to be null", obj.getId());
        obj.persist();
        obj.flush();
        Assert.assertNotNull("Expected 'Report' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void ReportIntegrationTest.testRemove() {
        Report obj = dod.getRandomReport();
        Assert.assertNotNull("Data on demand for 'Report' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Report' failed to provide an identifier", id);
        obj = Report.findReport(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'Report' with identifier '" + id + "'", Report.findReport(id));
    }
    
}
