// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.springsource.roo.extrack.server.domain;

import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;
import org.springsource.roo.extrack.server.domain.Employee;
import org.springsource.roo.extrack.server.domain.EmployeeDataOnDemand;
import org.springsource.roo.extrack.server.domain.Report;
import org.springsource.roo.extrack.server.domain.ReportDataOnDemand;

privileged aspect ReportDataOnDemand_Roo_DataOnDemand {
    
    declare @type: ReportDataOnDemand: @Component;
    
    private Random ReportDataOnDemand.rnd = new SecureRandom();
    
    private List<Report> ReportDataOnDemand.data;
    
    @Autowired
    private EmployeeDataOnDemand ReportDataOnDemand.employeeDataOnDemand;
    
    public Report ReportDataOnDemand.getNewTransientReport(int index) {
        Report obj = new Report();
        setApprovedSupervisor(obj, index);
        setCreated(obj, index);
        setDepartment(obj, index);
        setNotes(obj, index);
        setPurpose(obj, index);
        setReporter(obj, index);
        return obj;
    }
    
    public void ReportDataOnDemand.setApprovedSupervisor(Report obj, int index) {
        Employee approvedSupervisor = employeeDataOnDemand.getRandomEmployee();
        obj.setApprovedSupervisor(approvedSupervisor);
    }
    
    public void ReportDataOnDemand.setCreated(Report obj, int index) {
        Date created = new GregorianCalendar(Calendar.getInstance().get(Calendar.YEAR), Calendar.getInstance().get(Calendar.MONTH), Calendar.getInstance().get(Calendar.DAY_OF_MONTH), Calendar.getInstance().get(Calendar.HOUR_OF_DAY), Calendar.getInstance().get(Calendar.MINUTE), Calendar.getInstance().get(Calendar.SECOND) + new Double(Math.random() * 1000).intValue()).getTime();
        obj.setCreated(created);
    }
    
    public void ReportDataOnDemand.setDepartment(Report obj, int index) {
        String department = "department_" + index;
        obj.setDepartment(department);
    }
    
    public void ReportDataOnDemand.setNotes(Report obj, int index) {
        String notes = "notes_" + index;
        obj.setNotes(notes);
    }
    
    public void ReportDataOnDemand.setPurpose(Report obj, int index) {
        String purpose = "purpose_" + index;
        obj.setPurpose(purpose);
    }
    
    public void ReportDataOnDemand.setReporter(Report obj, int index) {
        Employee reporter = employeeDataOnDemand.getRandomEmployee();
        obj.setReporter(reporter);
    }
    
    public Report ReportDataOnDemand.getSpecificReport(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        Report obj = data.get(index);
        Long id = obj.getId();
        return Report.findReport(id);
    }
    
    public Report ReportDataOnDemand.getRandomReport() {
        init();
        Report obj = data.get(rnd.nextInt(data.size()));
        Long id = obj.getId();
        return Report.findReport(id);
    }
    
    public boolean ReportDataOnDemand.modifyReport(Report obj) {
        return false;
    }
    
    public void ReportDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = Report.findReportEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'Report' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<Report>();
        for (int i = 0; i < 10; i++) {
            Report obj = getNewTransientReport(i);
            try {
                obj.persist();
            } catch (ConstraintViolationException e) {
                StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getConstraintDescriptor()).append(":").append(cv.getMessage()).append("=").append(cv.getInvalidValue()).append("]");
                }
                throw new RuntimeException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
